### PR TITLE
Train on Python

### PR DESCRIPTION
**Pull request by mib32**

### CODE REVIEW

**Comment by mib32** [comment]
@ronaldtse To train on GPU, from the root directory use:
python3 python/train.py -i=./examples/thai-ipa/data/input.csv -t=./examples/thai-ipa/data/target.csv --device cuda

**Comment by mib32** [comment]
@ronaldtse Added tests and made them green. Can be merged?

**Comment by ronaldtse** [comment]
@mib32 yes we can merge this. Can you add documentation on how to run the python training on CPU as well? Thanks.

**Comment by mib32** [comment]
@ronaldtse Thanks, done

**Pull request merged**
