### PR TITLE
Test for ONNX runtime without libtorch installed 

### LINKED ISSUE #26: Test for ONNX runtime without libtorch installed
As per #25, we want to test a new GHA flow purely for the user gem `secryst` which uses `onnxruntime` without libtorch.

This issue is to make a new GHA flow that is separate, where a user machine only installs ONNX runtime and runs the examples/onnx spec.

### PR DESCRIPTION
**Pull request by mib32**
Closes #26

### CODE REVIEW

**Comment by mib32** [comment]
@ronaldtse Ah, interesting note - on MacOS you will still have to install "libomp" to run ONNX.

**Comment by mib32** [comment]
@ronaldtse All done, but one test is randomly failing now. Shall we merge anyways for now?

**Comment by ronaldtse** [comment]
@mib32 the failure is quite strange -- it looks like a real error due to mismatch of training/inference parameters ?

**Comment by ronaldtse** [comment]
All tests now pass but “Test model” fails on Ruby 2.6. Maybe we first merge this and leave a separate task for it.

**Pull request merged**
