### PR TITLE
Add support for ONNX models import

### LINKED ISSUE #3: Support import trained models via ONNX
Use https://github.com/ankane/onnxruntime

### PR DESCRIPTION
**Pull request by mib32**
Closes #3

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @mib32 -- can you help also add:
* a spec to test against an ONNX model package (`model.onnx` inside the zip)
* documentation on how to build the ONNX model package for Secryst (`model.onnx`, yaml files, etc.)
?

**Comment by mib32** [comment]
Yes, sure, will do

пт, 16 окт. 2020 г. в 02:42, Ronald Tse <notifications@github.com>:

**Comment by mib32** [comment]
@ronaldtse Okay, done

**Comment by ronaldtse** [comment]
Thanks @mib32!

**Pull request merged**
