### PR TITLE
Implement Armenian to Latin

### LINKED ISSUE #7: Implement Armenian transliteration training
According to: https://deeplanguageclass.github.io/lab/fairseq-transliteration/

Data here: https://github.com/deeplanguageclass/fairseq-transliteration-data

### PR DESCRIPTION
**Pull request by mib32**
Closes #7

### CODE REVIEW

**Comment by ronaldtse** [comment]
@mib32 looks great! Can you help also describe how to use `secryst translate` with this checkpoint file?

**Comment by ronaldtse** [comment]
Does `secryst translate` now take a Secryst "Model Package"? I'm getting this:

```sh
cd examples/arm-lat
head -10 data/input.csv > data/x.csv
bundle exec secryst translate --model-file checkpoints/checkpoint-90.zip -f data/x.csv

/Users/me/src/secryst/secryst/bin/secryst:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/me/src/secryst/secryst/lib/secryst/translator.rb:4: warning: The called method `initialize' is defined here
bundler: failed to load command: secryst (/Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/secryst)
Zip::Error: Zip end of central directory signature not found
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/central_directory.rb:143:in `get_e_o_c_d'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/central_directory.rb:103:in `read_e_o_c_d'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/central_directory.rb:136:in `read_from_stream'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:92:in `block in initialize'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:91:in `open'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:91:in `initialize'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:121:in `new'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubyzip-2.3.0/lib/zip/file.rb:121:in `open'
  /Users/me/src/secryst/secryst/lib/secryst/translator.rb:8:in `initialize'
  /Users/me/src/secryst/secryst/bin/secryst:13:in `new'
  /Users/me/src/secryst/secryst/bin/secryst:13:in `translate'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /Users/me/src/secryst/secryst/bin/secryst:27:in `<top (required)>'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/secryst:23:in `load'
  /Users/me/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/secryst:23:in `<top (required)>'

```

**Comment by mib32** [comment]
@ronaldtse You need to use '-t data/x.csv', not '-f data/x.csv'. Change -f to -t. It thinks that the x.csv is the model file :)

**Comment by ronaldtse** [comment]
@mib32 yes it works! Can you update the README to reflect this... Thanks!

**Comment by mib32** [comment]
> @mib32 yes it works! Can you update the README to reflect this... Thanks!

@ronaldtse Ok, done!

**Comment by ronaldtse** [comment]
Thanks @mib32 !

**Pull request merged**
