### PR TITLE
Add ability to resume from checkpoint

### LINKED ISSUE #28: Resume training of vocabulary from existing checkpoint file
In #27 Armenian to Latin training has been implemented, but if I want to resume training with the data set, I will need to start all over again. We should implement a mechanism to allow resumption of training from say, epoch 90 onwards.

### PR DESCRIPTION
**Pull request by mib32**
Closes #28

### CODE REVIEW

**Comment by ronaldtse** [comment]
@mib32 the tests are failing due to this:

```sh
../examples/onnx_import.rb:39:in `block in <main>': undefined method `stoi' for nil:NilClass (NoMethodError)
	from ../examples/onnx_import.rb:39:in `map!'
	from ../examples/onnx_import.rb:39:in `<main>'
```

**Comment by mib32** [comment]
@ronaldtse Something weird going on in macbook test, investigating...

**Comment by mib32** [comment]
@ronaldtse OK, updated libtorch, now it's perfrect

**Comment by ronaldtse** [comment]
@mib32 LGTM, can you also help update the README to indicate how to use this? Thanks!

**Comment by mib32** [comment]
> @mib32 LGTM, can you also help update the README to indicate how to use this? Thanks!

I actually did - take a look

**Comment by ronaldtse** [comment]
@mib32 ah, in the comments. Let's merge then.

**Pull request merged**
